# Generated by Django 3.1.5 on 2021-02-19 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Никнейм')),
                ('date_registration', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Последнее посещение')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Администратор')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Сотрудник')),
                ('is_active', models.BooleanField(default=True, verbose_name='Онлайн')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Супер администратор')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Пользователь(я)',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Russia', max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(blank=True, max_length=255, verbose_name='Район')),
                ('house', models.CharField(max_length=255)),
                ('apartment_number', models.CharField(blank=True, max_length=255, verbose_name='Квартира')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'db_table': 'address',
            },
        ),
    ]
