# Generated by Django 3.1.5 on 2021-03-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='related_customer', to='shop.Order', verbose_name='Заказы покупателя'),
        ),
    ]
