# Generated by Django 3.1.5 on 2021-02-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='orders',
            field=models.ManyToManyField(related_name='related_customer', to='shop.Order', verbose_name='Заказы покупателя'),
        ),
    ]
